apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
  selector:  # Corregido "setelctor" → "selector"
    app: my-react-app-label
